/*
 * File: pa1Strings.h
 * Description: Header file containing strings that are displayed to the user.
 * 
 * XXX DO NOT EDIT THIS FILE
 *
 */

#ifndef PA1_STRINGS_H /* Header guard */
#define PA1_STRINGS_H

#define INVALID_ARGS "Incorrect number of args.\n"
#define FILTER_ERR "Error opening input filter file\n"
#define LONG_USAGE "\n"\
  "Usage: ./spamFilter {-i dataFile | -h}"\
  "\n    -i dataFile -- The file containing the data"\
  "\n    -h          -- Displays this long usage message\n\n"\

#define SHORT_USAGE "\n"\
  "Usage: ./spamFilter {-i dataFile | -h}"\
  "\n\n"


/* Interactive Strings */
#define USER_PROMPT "Enter a word: "
#define WORD_NOT_FOUND "%s is not SPAM!\n"
#define WORD_FOUND "%s is SPAM!\n"

/* Extra Credit Strings */
#define LONG_USAGE_EC2 "\n"\
  "Usage: ./spamFilterEC2 -i dataFile [-h] [-s]"\
  "\n    -i dataFile -- The file containing the data"\
  "\n    -h          -- Displays this long usage message"\
  "\n    -s          -- Displays hash table statistics\n\n"

#define SHORT_USAGE_EC2 "\n"\
    "Usage: ./spamFilterEC2 -i dataFile [-h] [-s]"\
  "\n\n"
#define ARG_ERR "Missing file args\n"
#define STATISTICS "\nHash Table Statistics:\n\n"\
  "Number of empty entries: %d\n"\
  "Longest chain length: %d\n"\
  "Shortest chain length: %d\n"\
  "Average chain length: %d\n\n"

#endif
