/*
 * File: test.h
 * Description: Header file that provides test macro.
 *
 * XXX DO NOT EDIT THIS FILE.
 */
#ifndef TEST

#include <stdio.h>

/* Macro to explicity print tests that are run along with colorized result. */
#define TEST(EX) (void)((fprintf( stderr, "(%s:%d) %s:", __FILE__, __LINE__,\
                 #EX)) && ((EX && fprintf(stderr, "\t\x1b[32mPASSED\x1b[0m\n"))\
                 || (fprintf(stderr, "\t\x1b[31mFAILED\x1b[0m\n")) ))

#endif
